# permissions for end users to view httpmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: httpmonitor-viewer-role
rules:
- apiGroups:
  - monitoring.raisingthefloor.org
  resources:
  - httpmonitors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.raisingthefloor.org
  resources:
  - httpmonitors/status
  verbs:
  - get
