apiVersion: monitoring.raisingthefloor.org/v1alpha1
kind: HttpMonitor
metadata:
  name: check-downloads-page-external
spec:
  period: 1m
  requests:
    - name: check external access
      target_service: morphicweb
      method: GET
      url: "https://app.morphic.org/download"
      expected_response_codes: [200]
    - name: check external access2
      target_service: morphicweb
      method: GET
      url: "https://app.morphic.org/download"
      expected_response_codes: [200]