apiVersion: monitoring.raisingthefloor.org/v1alpha1
kind: HttpMonitor
metadata:
  name: check-downloads-page-external
spec:
  period: 30s
  requests:
    - name: check external access
      target_service: morphicweb
      method: GET
      url: '{API_URL}/download'
      expected_response_codes: [200]