apiVersion: monitoring.raisingthefloor.org/v1alpha1
kind: HttpMonitor
metadata:
  name: create-user
spec:
  period: 1m
  requests:
    - name: create user
      target_service: morphiclite
      method: POST
      url: "https://api.morphic.org/v1/register/username"
      body: |
        {
          "username": "testuser",
          "password": "password",
          "email": "test@raisingthefloor.org"
        }
      headers:
        Content-Type: ["application/json"]
      vars_from_response:
        - name: username
          from: body_json
          jsonpath: /user/id
      expected_response_codes: [200]

  cleanup:
    - name: delete user
      target_service: morphiclite
      method: DELETE
      url: "https://api.morphic.org/v1/user/{username}"
      expected_response_codes: [204]

