apiVersion: v1
kind: Service
metadata:
  name: mock-server
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: mock-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-server
  namespace: default
  labels:
    app: mock-server
spec:
  selector:
    matchLabels:
      app: mock-server
  replicas: 1
  template:
    metadata:
      labels:
        app: mock-server
    spec:
      containers:
        - args: []
          image: localhost:5000/mock-server
          name: manager
          ports:
            - name: http
              containerPort: 80
      terminationGracePeriodSeconds: 10

